### PR TITLE
enable multiple colors and stops

### PR DESCRIPTION
**Pull request by olivierpicault**
Your lib is almost doing what I wanted but I needed more than just start and end colors to get the gradient I exactly wanted.

### CODE REVIEW

**Comment by joostlek** [comment]
Thanks, but I think that it will become a bit harder to use (in my opinion). Maybe if I got some time I will try to come up with a cool way to keep it simple and extendable.

**Comment by cuberob** [comment]
It might make more sense to just allow the consumer of `GradientAppBar` to provide a `BoxDecoration` or Gradient directly. That way you can do whatever you want as a consumer but still only have to provide a single, well documented, argument. What do you think?

**Comment by joostlek** [comment]
That's a damn good idea, I'll try to release that in the next week

**Comment by joostlek** [comment]
So I now released an update (we're at 0.1.3 now, due to me getting this to work with CI (it now auto publishes to pub :D)).

Now you can add your own gradient by just giving it as a property:

`Scaffold(
        appBar: GradientAppBar(
          title: Text(widget.title),
          gradient: <INSERT YOUR GRADIENT HERE>,
          bottom: TabBar(tabs: <Widget>[
            Tab(
              icon: Icon(Icons.home),
              text: 'Home',
            ),
            Tab(
              icon: Icon(Icons.store),
              text: 'Store',
            )
          ]),
        ),`

So now you can add whatever gradient you want 👍

**Comment by cuberob** [comment]
Cool, thanks! ( lekker bezig ;) )

**Pull request closed without merging**
